# AFRped data

In [1]:
versioninfo()

Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)


## Retrieve genotype data from pedigree file

In [2]:
@time rawdata = readcsv("AFRped_geno.txt", Float32)

  9.371475 seconds (174.50 M allocations: 4.687 GiB, 8.81% gc time)


1325×36499 Array{Float32,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0 

In [3]:
people = 664
X = rawdata[1:people, 1:(end - 1)]'

36498×664 Array{Float32,2}:
 0.0  0.0  1.0  0.0  1.0  1.0  0.0  1.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  

In [4]:
if eltype(rawdata) <: Integer
    H = (rawdata[(people + 1):end, 1:(end - 1)] .>> 1).'
else
    H = (rawdata[(people + 1):end, 1:(end - 1)] / 2).'
end

36498×661 Array{Float32,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  

## Phase + impute by moving window (using flanking windows)

In [5]:
using BenchmarkTools, MendelImpute, NullableArrays

srand(123)
missingprop = 0.1
Xm = NullableArray(X, full(sprand(Bool, size(X, 1), size(X, 2), missingprop)))
missing_true = round.(Int, X[Xm.isnull])
Xm

36498×664 NullableArrays.NullableArray{Float32,2}:
 0.0    0.0    1.0    0.0    1.0    1.0    …  #NULL  0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    #NULL     0.0    0.0  0.0    0.0    #NULL
 0.0    0.0    0.0    0.0    #NULL  0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    #NULL  0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    #NULL  0.0    0.0    0.0    0.0    …  0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  #NULL  0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0    …  0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    #NULL  #NULL
 0.0    0.0  

In [6]:
@time ph = phase(Xm, H, 400);

Imputing SNPs 1:400
Imputing SNPs 401:800
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 801:1200
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 1201:1600
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 1601:2000
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 2001:2400
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 2401:2800
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 2801:3200
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 3201:3600
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 3601:4000
happair = (205, 76)
bkpts = (-1, 750)
Imputing SNPs 4001:4400
happair = (205, 264)
bkpts = (-1, 0)
Imputing SNPs 4401:4800
happair = (205, 83)
bkpts = (-1, 0)
Imputing SNPs 4801:5200
happair = (205, 120)
bkpts = (-1, 770)
Imputing SNPs 5201:5600
happair = (205, 338)
bkpts = (-1, 153)
Imputing SNPs 5601:6000
happair = (205, 236)
bkpts = (-1, 0)
Imputing SNPs 6001:6400
happair = (205, 236)
bkpts = (-1, -1)
Imputing SNPs 6401:6800
happair = (205, 404)
bkpts = (-

In [7]:
ph[1]

MendelImpute.HaplotypeMosaicPair(MendelImpute.HaplotypeMosaic(36498, [1, 8401, 9201, 9601, 10001, 10401, 11618, 11601, 12001, 13601  …  18401, 18801, 19201, 20801, 21201, 23201, 24001, 24401, 25601, 26001], [205, 24, 9, 51, 3, 194, 42, 2, 205, 194  …  160, 286, 194, 136, 205, 49, 19, 137, 14, 205]), MendelImpute.HaplotypeMosaic(36498, [1, 3951, 3601, 4001, 5171, 4954, 5201, 6789, 6739, 6801  …  21201, 23201, 24001, 24401, 27601, 28001, 28401, 28801, 30001, 30401], [205, 76, 264, 83, 120, 338, 236, 404, 490, 205  …  236, 235, 561, 236, 24, 376, 54, 236, 173, 236]))

In [8]:
impute!(Xm.values, H, ph)

In [9]:
missing_impute = round.(Int, Xm.values[Xm.isnull])
error = countnz(missing_true .≠ missing_impute) / length(missing_true)

0.0036607118921582983

In [10]:
Xm

36498×664 NullableArrays.NullableArray{Float32,2}:
 0.0    0.0    1.0    0.0    1.0    1.0    …  #NULL  0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    #NULL     0.0    0.0  0.0    0.0    #NULL
 0.0    0.0    0.0    0.0    #NULL  0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    #NULL  0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    #NULL  0.0    0.0    0.0    0.0    …  0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  #NULL  0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0    …  0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    #NULL  #NULL
 0.0    0.0  

## Profiling

In [11]:
Profile.clear()
@profile phase(Xm, H, 400)
Profile.print(format=:flat)

Imputing SNPs 1:400
Imputing SNPs 401:800
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 801:1200
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 1201:1600
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 1601:2000
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 2001:2400
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 2401:2800
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 2801:3200
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 3201:3600
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 3601:4000
happair = (205, 76)
bkpts = (-1, 457)
Imputing SNPs 4001:4400
happair = (205, 264)
bkpts = (-1, 0)
Imputing SNPs 4401:4800
happair = (205, 83)
bkpts = (-1, 0)
Imputing SNPs 4801:5200
happair = (205, 120)
bkpts = (-1, 770)
Imputing SNPs 5201:5600
happair = (205, 338)
bkpts = (-1, 153)
Imputing SNPs 5601:6000
happair = (205, 236)
bkpts = (-1, 0)
Imputing SNPs 6001:6400
happair = (111, 236)
bkpts = (211, -1)
Imputing SNPs 6401:6800
happair = (205, 404)
bkpts = (

  8814 ...pute/src/haplotyping.jl   246 haploimpute!(::NullableArrays.Nulla... 
   143 ...pute/src/haplotyping.jl   248 haploimpute!(::NullableArrays.Nulla... 
    14 ...pute/src/haplotyping.jl    32 haplopair!(::Tuple{Array{Int64,1},A... 
  8562 ...pute/src/haplotyping.jl    34 haplopair!(::Tuple{Array{Int64,1},A... 
    39 ...pute/src/haplotyping.jl   102 haplopair!(::Array{Float32,2}, ::Su... 
     9 ...pute/src/haplotyping.jl   103 haplopair!(::Array{Float32,2}, ::Su... 
    55 ...pute/src/haplotyping.jl   104 haplopair!(::Array{Float32,2}, ::Su... 
     1 ...pute/src/haplotyping.jl   107 haplopair!(::Array{Float32,2}, ::Su... 
    52 ...pute/src/haplotyping.jl   110 haplopair!(::Array{Float32,2}, ::Su... 
    14 ...pute/src/haplotyping.jl   111 haplopair!(::Array{Float32,2}, ::Su... 
  8576 ...pute/src/haplotyping.jl   115 haplopair!(::Array{Float32,2}, ::Su... 
     1 ...pute/src/haplotyping.jl   117 haplopair!(::Array{Float32,2}, ::Su... 
    67 ...pute/src/haplotyping.jl   118 

## Effect of window size on accuracy and efficiency

In [15]:
width_range = 100:100:1000
timing = zeros(length(width_range))
errate = zeros(length(width_range))
for i in eachindex(width_range)
    tic()
    copy!(Xm.values, rawdata[1:people, 1:(end - 1)]')
    ph = phase(Xm, H, width_range[i], false)
    impute!(Xm.values, H, ph)
    timing[i] = toq()
    missing_impute = round.(Int, Xm.values[Xm.isnull])
    errate[i] = countnz(missing_true .≠ missing_impute) / length(missing_true)
    println("width = $(width_range[i]), time = $(timing[i]), error rate = $(errate[i])")
end

width = 100, time = 44.652082362, error rate = 0.009299016565174983
width = 200, time = 23.251482066, error rate = 0.00504976976200836
width = 300, time = 16.099439054, error rate = 0.0038203215701962953
width = 400, time = 12.630925796, error rate = 0.0036607118921582983
width = 500, time = 11.166686167, error rate = 0.0037988753085477786
width = 600, time = 9.042634645, error rate = 0.004253783512361502
width = 700, time = 8.137103798, error rate = 0.004584550855479004
width = 800, time = 7.262145625, error rate = 0.005146690367535309
width = 900, time = 6.735577601, error rate = 0.005656039081687573
width = 1000, time = 6.250194499, error rate = 0.006445838909705052


In [16]:
using Plots
gr()

plot(width_range, timing; xlabel = "Window width", 
    ylabel = "Run time in seconds", leg = false)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 250 
 
 
 500 
 
 
 750 
 
 
 1000 
 
 
 10 
 
 
 20 
 
 
 30 
 
 
 40 
 
 
 Window width 
 
 
 Run time in seconds

In [17]:
plot(width_range, errate; xlabel = "Window width", 
    ylabel = "Error rate", leg = false)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 250 
 
 
 500 
 
 
 750 
 
 
 1000 
 
 
 0.0050 
 
 
 0.0075 
 
 
 Window width 
 
 
 Error rate