# AFRped data

In [1]:
versioninfo()

Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)


## Retrieve genotype data from pedigree file

In [2]:
#;ls -al

In [3]:
## cut out the first 6 fields in the pedigree file
#;cut -d ',' -f7- AFRped.txt > AFRped_geno.txt

In [4]:
#;ls -al

In [5]:
@time rawdata = readcsv("AFRped_geno.txt", Float32)

  9.272943 seconds (174.50 M allocations: 4.687 GiB, 8.06% gc time)


1325×36499 Array{Float32,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0 

In [6]:
people = 664
X = rawdata[1:people, 1:(end - 1)]'

36498×664 Array{Float32,2}:
 0.0  0.0  1.0  0.0  1.0  1.0  0.0  1.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  

In [7]:
if eltype(rawdata) <: Integer
    H = (rawdata[(people + 1):end, 1:(end - 1)] .>> 1)'
else
    H = (rawdata[(people + 1):end, 1:(end - 1)] / 2)'
end

36498×661 Array{Float32,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  

## phase+impute a fixed window

In [8]:
using BenchmarkTools, MendelImpute, NullableArrays

X1 = X[:, 1:1200]
H1 = H[:, 1:1200]
missingprop = 0.1
Xm = NullableArray(X1, full(sprand(Bool, size(X1, 1), size(X1, 2), missingprop)))
missing_true = round.(Int, X1[Xm.isnull])

79586-element Array{Int64,1}:
 1
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [18]:
n, d = size(X1, 1), size(H1, 1)
M = zeros(eltype(H), d, d)
N = zeros(eltype(X), n, d)
happair  = zeros(Int, n), zeros(Int, n)
hapscore = zeros(eltype(N), n)
@time haploimpute!(Xm, H1, M, N, happair, hapscore)
missing_impute = round.(Int, Xm.values[Xm.isnull])
error = countnz(missing_true .≠ missing_impute) / length(missing_true)

  0.177176 seconds (4 allocations: 160 bytes)


0.00284172706901516

In [9]:
@benchmark haploimpute!(Xm, H1, M, N, happair, hapscore)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     129.398 ms (0.00% GC)
  median time:      134.146 ms (0.00% GC)
  mean time:        139.546 ms (0.00% GC)
  maximum time:     182.269 ms (0.00% GC)
  --------------
  samples:          36
  evals/sample:     1

In [10]:
Profile.clear()
@profile haploimpute!(Xm, H1, M, N, happair, hapscore)
Profile.print(format=:flat)

 Count File                        Line Function                               
    99 ./<missing>                   -1 anonymous                              
     3 ./abstractarray.jl           572 copy!(::Array{Any,1}, ::Core.Infere... 
     1 ./inference.jl              1681 abstract_call(::Any, ::Array{Any,1}... 
     2 ./inference.jl              1882 abstract_call(::Any, ::Array{Any,1}... 
     2 ./inference.jl              1401 abstract_call_gf_by_type(::Any, ::A... 
     6 ./inference.jl              1935 abstract_eval(::Any, ::Array{Any,1}... 
     3 ./inference.jl              1886 abstract_eval_call(::Expr, ::Array{... 
     3 ./inference.jl              1912 abstract_eval_call(::Expr, ::Array{... 
     1 ./inference.jl              1044 apply_type_tfunc(::ANY, ::Vararg{AN... 
     1 ./inference.jl              1192 builtin_tfunction(::Any, ::Array{An... 
     1 ./inference.jl              2564 typeinf_code(::Core.MethodInstance,... 
     2 ./inference.jl              2517 

## Phase + impute by moving window (using flanking windows)

In [8]:
using BenchmarkTools, MendelImpute, NullableArrays

srand(123)
missingprop = 0.1
Xm = NullableArray(X, full(sprand(Bool, size(X, 1), size(X, 2), missingprop)))
missing_true = round.(Int, X[Xm.isnull])

@time haploimpute!(Xm, H, 400)

Imputing SNPs 1:400


Imputing SNPs 401:800
[205, 205]
Imputing SNPs 801:1200
[205, 205]
Imputing SNPs 1201:1600
[205, 205]
Imputing SNPs 1601:2000
[205, 205]
Imputing SNPs 2001:2400
[205, 205]
Imputing SNPs 2401:2800
[205, 205]
Imputing SNPs 2801:3200
[205, 205]
Imputing SNPs 3201:3600
[205, 205]
Imputing SNPs 3601:4000
[205, 205]
Imputing SNPs 4001:4400
[205, 205]
Imputing SNPs 4401:4800
[205, 264]
Imputing SNPs 4801:5200
[83, 205]
Imputing SNPs 5201:5600
[120, 205]
Imputing SNPs 5601:6000
[205, 338]
Imputing SNPs 6001:6400
[205, 236]
Imputing SNPs 6401:6800
[205, 236]
Imputing SNPs 6801:7200
[205, 404]
Imputing SNPs 7201:7600
[205, 515]
Imputing SNPs 7601:8000
[205, 205]
Imputing SNPs 8001:8400
[205, 205]
Imputing SNPs 8401:8800
[205, 205]
Imputing SNPs 8801:9200
[205, 205]
Imputing SNPs 9201:9600
[24, 51]
Imputing SNPs 9601:10000
[4, 24]
Imputing SNPs 10001:10400
[9, 194]
Imputing SNPs 10401:10800
[51, 215]
Imputing SNPs 10801:11200
[3, 128]
Imputing SNPs 11201:11600
[128, 194]
Imputing SNPs 11601:12000

In [9]:
missing_impute = round.(Int, Xm.values[Xm.isnull])
error = countnz(missing_true .≠ missing_impute) / length(missing_true)

0.004470316758469656

## Profiling

In [11]:
Profile.clear()
@profile haploimpute!(Xm, H, 400)
Profile.print(format=:flat)

Imputing SNPs 1:400
Imputing SNPs 401:800
[205, 205]
Imputing SNPs 801:1200
[205, 205]
Imputing SNPs 1201:1600
[205, 205]
Imputing SNPs 1601:2000
[205, 205]
Imputing SNPs 2001:2400
[205, 205]
Imputing SNPs 2401:2800
[205, 205]
Imputing SNPs 2801:3200
[205, 205]
Imputing SNPs 3201:3600
[205, 205]
Imputing SNPs 3601:4000
[205, 205]
Imputing SNPs 4001:4400
[76, 205]
Imputing SNPs 4401:4800
[205, 264]
Imputing SNPs 4801:5200
[205, 379]
Imputing SNPs 5201:5600
[205, 379]
Imputing SNPs 5601:6000
[205, 338]
Imputing SNPs 6001:6400
[205, 236]
Imputing SNPs 6401:6800
[236, 374]
Imputing SNPs 6801:7200
[205, 515]
Imputing SNPs 7201:7600
[205, 515]
Imputing SNPs 7601:8000
[205, 205]
Imputing SNPs 8001:8400
[205, 205]
Imputing SNPs 8401:8800
[205, 205]
Imputing SNPs 8801:9200
[205, 403]
Imputing SNPs 9201:9600
[24, 51]
Imputing SNPs 9601:10000
[24, 51]
Imputing SNPs 10001:10400
[9, 194]
Imputing SNPs 10401:10800
[128, 194]
Imputing SNPs 10801:11200
[128, 194]
Imputing SNPs 11201:11600
[128, 194]
I

## Effect of window size on accuracy and efficiency

In [12]:
width_range = 100:100:1000
timing = zeros(length(width_range))
errate = zeros(length(width_range))
for i in eachindex(width_range)
    tic()
    copy!(Xm.values, rawdata[1:people, 1:(end - 1)])
    haploimpute!(Xm, H, width_range[i], false)
    timing[i] = toq()
    missing_impute = round.(Int, Xm.values[Xm.isnull])
    errate[i] = countnz(missing_true .≠ missing_impute) / length(missing_true)
    println("width = $(width_range[i]), time = $(timing[i]), error rate = $(errate[i])")
end

width = 100, time = 44.038732141, error rate = 0.008510390794868273
width = 200, time = 23.243300354, error rate = 0.004885709300296632
width = 300, time = 15.797048683, error rate = 0.004359765416652744
width = 400, time = 12.415923102, error rate = 0.004464129183367963
width = 500, time = 10.186983241, error rate = 0.004872509140079688
width = 600, time = 8.592527449, error rate = 0.0055741801566116505
width = 700, time = 7.546099573, error rate = 0.006100124040255539
width = 800, time = 6.791786047, error rate = 0.006909458863556956
width = 900, time = 6.060311093, error rate = 0.007568229359383849
width = 1000, time = 5.549981368, error rate = 0.008076848032742997


In [15]:
using Plots
gr()

plot(width_range, timing; xlabel = "Window width", 
    ylabel = "Run time in seconds", leg = false)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 250 
 
 
 500 
 
 
 750 
 
 
 1000 
 
 
 10 
 
 
 20 
 
 
 30 
 
 
 40 
 
 
 Window width 
 
 
 Run time in seconds

In [16]:
plot(width_range, errate; xlabel = "Window width", 
    ylabel = "Error rate", leg = false)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 250 
 
 
 500 
 
 
 750 
 
 
 1000 
 
 
 0.005 
 
 
 0.006 
 
 
 0.007 
 
 
 0.008 
 
 
 Window width 
 
 
 Error rate