# AFRped data

In [1]:
versioninfo()

Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)


## Retrieve genotype data from pedigree file

In [2]:
#;ls -al

In [3]:
## cut out the first 6 fields in the pedigree file
#;cut -d ',' -f7- AFRped.txt > AFRped_geno.txt

In [4]:
#;ls -al

In [5]:
@time rawdata = readcsv("AFRped_geno.txt", Float32)

  9.012828 seconds (174.50 M allocations: 4.687 GiB, 8.46% gc time)


1325×36499 Array{Float32,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0 

In [6]:
people = 664
X = rawdata[1:people, 1:(end - 1)]'

36498×664 Array{Float32,2}:
 0.0  0.0  1.0  0.0  1.0  1.0  0.0  1.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  

In [7]:
if eltype(rawdata) <: Integer
    H = (rawdata[(people + 1):end, 1:(end - 1)] .>> 1)'
else
    H = (rawdata[(people + 1):end, 1:(end - 1)] / 2)'
end

36498×661 Array{Float32,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  

## Phase + impute by moving window (using flanking windows)

In [8]:
using BenchmarkTools, MendelImpute, NullableArrays

srand(123)
missingprop = 0.1
Xm = NullableArray(X, full(sprand(Bool, size(X, 1), size(X, 2), missingprop)))
missing_true = round.(Int, X[Xm.isnull])
Xm

36498×664 NullableArrays.NullableArray{Float32,2}:
 0.0    0.0    1.0    0.0    1.0    1.0    …  #NULL  0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    #NULL     0.0    0.0  0.0    0.0    #NULL
 0.0    0.0    0.0    0.0    #NULL  0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    #NULL  0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    #NULL  0.0    0.0    0.0    0.0    …  0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  #NULL  0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0    …  0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    #NULL  #NULL
 0.0    0.0  

In [9]:
@time ph = phase(Xm, H, 400)

Imputing SNPs 1:400
Imputing SNPs 401:800
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 801:1200
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 1201:1600
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 1601:2000
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 2001:2400
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 2401:2800
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 2801:3200
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 3201:3600
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 3601:4000
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 4001:4400
happair = (205, 264)
bkpts = (-1, 350)
Imputing SNPs 4401:4800
happair = (205, 83)
bkpts = (-1, 0)
Imputing SNPs 4801:5200
happair = (205, 379)
bkpts = (-1, 770)
Imputing SNPs 5201:5600
happair = (205, 338)
bkpts = (-1, 153)
Imputing SNPs 5601:6000
happair = (205, 236)
bkpts = (-1, 0)
Imputing SNPs 6001:6400
happair = (205, 236)
bkpts = (-1, -1)
Imputing SNPs 6401:6800
happair = (205, 515)
bkpts = 

664-element Array{MendelImpute.HaplotypeMosaicPair,1}:
 MendelImpute.HaplotypeMosaicPair(MendelImpute.HaplotypeMosaic(36498, [1, 8401, 9201, 9601, 10801, 11601, 12001, 14801, 15201, 18401, 18801, 20801, 21201, 21601, 23201, 24401, 25601, 26001], [205, 24, 9, 128, 205, 2, 194, 74, 194, 160, 194, 136, 158, 236, 49, 137, 14, 205]), MendelImpute.HaplotypeMosaic(36498, [1, 3951, 4001, 5171, 4954, 5201, 6789, 6801, 8754, 8401  …  12001, 18401, 20801, 21201, 23201, 24001, 27601, 28001, 28401, 28801], [205, 264, 83, 379, 338, 236, 515, 205, 403, 51  …  236, 205, 190, 205, 235, 236, 24, 7, 54, 236]))                                         
 MendelImpute.HaplotypeMosaicPair(MendelImpute.HaplotypeMosaic(36498, [1, 5586, 5601, 9601, 10401, 10801, 11601, 12001, 20801, 21201, 22401, 22801, 24401, 24801, 25601, 26001], [205, 139, 194, 111, 128, 205, 137, 205, 136, 194, 115, 194, 105, 137, 14, 205]), MendelImpute.HaplotypeMosaic(36498, [1, 2801, 4001, 9201, 9601, 10801, 11601, 12001, 18959, 19142, 19

In [10]:
ph[1]

MendelImpute.HaplotypeMosaicPair(MendelImpute.HaplotypeMosaic(36498, [1, 8401, 9201, 9601, 10801, 11601, 12001, 14801, 15201, 18401, 18801, 20801, 21201, 21601, 23201, 24401, 25601, 26001], [205, 24, 9, 128, 205, 2, 194, 74, 194, 160, 194, 136, 158, 236, 49, 137, 14, 205]), MendelImpute.HaplotypeMosaic(36498, [1, 3951, 4001, 5171, 4954, 5201, 6789, 6801, 8754, 8401  …  12001, 18401, 20801, 21201, 23201, 24001, 27601, 28001, 28401, 28801], [205, 264, 83, 379, 338, 236, 515, 205, 403, 51  …  236, 205, 190, 205, 235, 236, 24, 7, 54, 236]))

In [11]:
impute!(Xm.values, H, ph)

In [12]:
missing_impute = round.(Int, Xm.values[Xm.isnull])
error = countnz(missing_true .≠ missing_impute) / length(missing_true)

0.003160436596395791

In [13]:
Xm

36498×664 NullableArrays.NullableArray{Float32,2}:
 0.0    0.0    1.0    0.0    1.0    1.0    …  #NULL  0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    #NULL     0.0    0.0  0.0    0.0    #NULL
 0.0    0.0    0.0    0.0    #NULL  0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    #NULL  0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    #NULL  0.0    0.0    0.0    0.0    …  0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  #NULL  0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0    …  0.0    0.0  0.0    0.0    0.0  
 0.0    0.0    0.0    0.0    0.0    0.0       0.0    0.0  0.0    #NULL  #NULL
 0.0    0.0  

## Profiling

In [14]:
Profile.clear()
@profile phase(Xm, H, 400)
Profile.print(format=:flat)

Imputing SNPs 1:400
Imputing SNPs 401:800
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 801:1200
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 1201:1600
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 1601:2000
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 2001:2400
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 2401:2800
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 2801:3200
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 3201:3600
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 3601:4000
happair = (205, 205)
bkpts = (-1, -1)
Imputing SNPs 4001:4400
happair = (205, 264)
bkpts = (-1, 350)
Imputing SNPs 4401:4800
happair = (205, 83)
bkpts = (-1, 0)
Imputing SNPs 4801:5200
happair = (205, 120)
bkpts = (-1, 770)
Imputing SNPs 5201:5600
happair = (205, 338)
bkpts = (-1, 153)
Imputing SNPs 5601:6000
happair = (205, 236)
bkpts = (-1, 0)
Imputing SNPs 6001:6400
happair = (205, 236)
bkpts = (-1, -1)
Imputing SNPs 6401:6800
happair = (205, 515)
bkpts = 

     1 ...pute/src/haplotyping.jl   440 continue_haplotype(::SubArray{Nulla... 
    38 ...pute/src/haplotyping.jl   442 continue_haplotype(::SubArray{Nulla... 
    24 ...pute/src/haplotyping.jl   445 continue_haplotype(::SubArray{Nulla... 
    23 ...pute/src/haplotyping.jl   448 continue_haplotype(::SubArray{Nulla... 
 17994 ...pute/src/haplotyping.jl   455 continue_haplotype(::NullableArrays... 
 17760 ...pute/src/haplotyping.jl   458 continue_haplotype(::NullableArrays... 
    18 ...pute/src/haplotyping.jl   177 fillgeno!(::SubArray{Float32,2,Arra... 
    19 ...pute/src/haplotyping.jl   148 fillmissing!(::NullableArrays.Nulla... 
    33 ...pute/src/haplotyping.jl   149 fillmissing!(::NullableArrays.Nulla... 
     2 ...pute/src/haplotyping.jl   150 fillmissing!(::NullableArrays.Nulla... 
   228 ...pute/src/haplotyping.jl   243 haploimpute!(::NullableArrays.Nulla... 
  8816 ...pute/src/haplotyping.jl   246 haploimpute!(::NullableArrays.Nulla... 
    54 ...pute/src/haplotyping.jl   248 

## Effect of window size on accuracy and efficiency

In [12]:
width_range = 100:100:1000
timing = zeros(length(width_range))
errate = zeros(length(width_range))
for i in eachindex(width_range)
    tic()
    copy!(Xm.values, rawdata[1:people, 1:(end - 1)])
    haploimpute!(Xm, H, width_range[i], false)
    timing[i] = toq()
    missing_impute = round.(Int, Xm.values[Xm.isnull])
    errate[i] = countnz(missing_true .≠ missing_impute) / length(missing_true)
    println("width = $(width_range[i]), time = $(timing[i]), error rate = $(errate[i])")
end

width = 100, time = 44.038732141, error rate = 0.008510390794868273
width = 200, time = 23.243300354, error rate = 0.004885709300296632
width = 300, time = 15.797048683, error rate = 0.004359765416652744
width = 400, time = 12.415923102, error rate = 0.004464129183367963
width = 500, time = 10.186983241, error rate = 0.004872509140079688
width = 600, time = 8.592527449, error rate = 0.0055741801566116505
width = 700, time = 7.546099573, error rate = 0.006100124040255539
width = 800, time = 6.791786047, error rate = 0.006909458863556956
width = 900, time = 6.060311093, error rate = 0.007568229359383849
width = 1000, time = 5.549981368, error rate = 0.008076848032742997


In [15]:
using Plots
gr()

plot(width_range, timing; xlabel = "Window width", 
    ylabel = "Run time in seconds", leg = false)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 250 
 
 
 500 
 
 
 750 
 
 
 1000 
 
 
 10 
 
 
 20 
 
 
 30 
 
 
 40 
 
 
 Window width 
 
 
 Run time in seconds

In [16]:
plot(width_range, errate; xlabel = "Window width", 
    ylabel = "Error rate", leg = false)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 250 
 
 
 500 
 
 
 750 
 
 
 1000 
 
 
 0.005 
 
 
 0.006 
 
 
 0.007 
 
 
 0.008 
 
 
 Window width 
 
 
 Error rate