# GBR data

In [1]:
versioninfo()

Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)


## Read in genotype data and reference panel

In [12]:
rawdata = readcsv("GBR_data.csv", Float32)

1182×163476 Array{Float32,2}:
 0.0  1.0  1.0  1.0  2.0  2.0  1.0  0.0  …  1.0  0.0  0.0  1.0  0.0  0.0  1.0
 0.0  0.0  0.0  1.0  1.0  2.0  1.0  0.0     1.0  0.0  1.0  0.0  1.0  1.0  0.0
 2.0  1.0  1.0  1.0  0.0  2.0  1.0  1.0     0.0  1.0  1.0  0.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0     0.0  1.0  1.0  0.0  1.0  1.0  1.0
 1.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  …  1.0  0.0  2.0  0.0  0.0  0.0  0.0
 1.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 1.0  0.0  1.0  1.0  2.0  0.0  1.0  1.0     0.0  1.0  1.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0     1.0  1.0  1.0  0.0  0.0  1.0  0.0
 2.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  2.0  0.0
 0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  …  0.0  0.0  1.0  0.0  1.0  0.0  0.0
 0.0  1.0  2.0  1.0  1.0  0.0  1.0  0.0     0.0  1.0  0.0  0.0  1.0  1.0  1.0
 2.0  0.0  1.0  0.0  0.0  1.0  2.0

In [16]:
people = 1000
X = rawdata[1:people, :]

1000×163476 Array{Float32,2}:
 0.0  1.0  1.0  1.0  2.0  2.0  1.0  0.0  …  1.0  0.0  0.0  1.0  0.0  0.0  1.0
 0.0  0.0  0.0  1.0  1.0  2.0  1.0  0.0     1.0  0.0  1.0  0.0  1.0  1.0  0.0
 2.0  1.0  1.0  1.0  0.0  2.0  1.0  1.0     0.0  1.0  1.0  0.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0     0.0  1.0  1.0  0.0  1.0  1.0  1.0
 1.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  …  1.0  0.0  2.0  0.0  0.0  0.0  0.0
 1.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 1.0  0.0  1.0  1.0  2.0  0.0  1.0  1.0     0.0  1.0  1.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0     1.0  1.0  1.0  0.0  0.0  1.0  0.0
 2.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  2.0  0.0
 0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  …  0.0  0.0  1.0  0.0  1.0  0.0  0.0
 0.0  1.0  2.0  1.0  1.0  0.0  1.0  0.0     0.0  1.0  0.0  0.0  1.0  1.0  1.0
 2.0  0.0  1.0  0.0  0.0  1.0  2.0

In [17]:
H = rawdata[(people + 1):end, :]

182×163476 Array{Float32,2}:
 0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0     1.0  1.0  0.0  0.0  1.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0     0.0  1.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0     0.0  0.0  0.0  1.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0     0.0  1.0  1.0  1.0  0.0  0.0  0.0
 1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  …  0.0  1.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0     0.0  0.0  1.0  0.0  1.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0     0.0  1.0  1.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0     0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  …  1.0  0.0  0.0  0.0  1.0  1.0  1.0
 1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0     1.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  1.0  0.0  0.0  1.0 

# Phase+impute a fixed window

In [24]:
using BenchmarkTools, MendelImpute, NullableArrays

X1 = X[:, 1:800]
H1 = H[:, 1:800]
missingprop = 0.1
Xm = NullableArray(X1, full(sprand(Bool, size(X1, 1), size(X1, 2), missingprop)))
missing_true = round.(Int, X1[Xm.isnull])

80743-element Array{Int64,1}:
 1
 1
 0
 2
 0
 0
 1
 1
 0
 0
 0
 2
 1
 ⋮
 0
 0
 0
 0
 1
 0
 0
 0
 2
 2
 0
 0

In [25]:
n, d = size(X1, 1), size(H1, 1)
M = zeros(eltype(H), d, d)
N = zeros(eltype(X), n, d)
happair  = zeros(Int, n), zeros(Int, n)
hapscore = zeros(eltype(N), n)
@time haploimpute!(Xm, H1, M, N, happair, hapscore)
missing_impute = round.(Int, Xm.values[Xm.isnull])
error = countnz(missing_true .≠ missing_impute) / length(missing_true)

  0.026792 seconds (4 allocations: 160 bytes)


8.669482184214111e-5

In [26]:
@benchmark haploimpute!(Xm, H1, M, N, happair, hapscore)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     20.898 ms (0.00% GC)
  median time:      21.271 ms (0.00% GC)
  mean time:        21.410 ms (0.00% GC)
  maximum time:     23.016 ms (0.00% GC)
  --------------
  samples:          234
  evals/sample:     1

In [27]:
Profile.clear()
@profile haploimpute!(Xm, H1, M, N, happair, hapscore)
Profile.print(format=:flat)

 Count File                        Line Function                               
    20 ./<missing>                   -1 anonymous                              
     1 ./inference.jl               231 Core.Inference.InferenceState(::Cor... 
     1 ./inference.jl              2564 typeinf_code(::Core.MethodInstance,... 
     1 ./inference.jl              2603 typeinf_ext(::Core.MethodInstance, ... 
     1 ./inference.jl              2484 typeinf_frame(::Core.MethodInstance... 
    21 ./loading.jl                 515 include_string(::String, ::String)     
    20 ./profile.jl                  23 macro expansion                        
     1 ./simdloop.jl                 73 macro expansion                        
    21 ./task.jl                    335 (::IJulia.##11#14)()                   
    21 ...IJulia/src/eventloop.jl     8 eventloop(::ZMQ.Socket)                
    21 .../src/execute_request.jl   160 execute_request(::ZMQ.Socket, ::IJu... 
     1 ...pute/src/haplotyping.jl   148 

## Phase + impute by moving window (using flanking windows)

In [28]:
using BenchmarkTools, MendelImpute, NullableArrays

srand(123)
missingprop = 0.1
Xm = NullableArray(X, full(sprand(Bool, size(X, 1), size(X, 2), missingprop)))
missing_true = round.(Int, X[Xm.isnull])

@time haploimpute!(Xm, H, 400)

Imputing SNPs 1:400
Imputing SNPs 401:800
Imputing SNPs 801:1200
Imputing SNPs 1201:1600
Imputing SNPs 1601:2000
Imputing SNPs 2001:2400
Imputing SNPs 2401:2800
Imputing SNPs 2801:3200
Imputing SNPs 3201:3600
Imputing SNPs 3601:4000
Imputing SNPs 4001:4400
Imputing SNPs 4401:4800
Imputing SNPs 4801:5200
Imputing SNPs 5201:5600
Imputing SNPs 5601:6000
Imputing SNPs 6001:6400
Imputing SNPs 6401:6800
Imputing SNPs 6801:7200
Imputing SNPs 7201:7600
Imputing SNPs 7601:8000
Imputing SNPs 8001:8400
Imputing SNPs 8401:8800
Imputing SNPs 8801:9200
Imputing SNPs 9201:9600
Imputing SNPs 9601:10000
Imputing SNPs 10001:10400
Imputing SNPs 10401:10800
Imputing SNPs 10801:11200
Imputing SNPs 11201:11600
Imputing SNPs 11601:12000
Imputing SNPs 12001:12400
Imputing SNPs 12401:12800
Imputing SNPs 12801:13200
Imputing SNPs 13201:13600
Imputing SNPs 13601:14000
Imputing SNPs 14001:14400
Imputing SNPs 14401:14800
Imputing SNPs 14801:15200
Imputing SNPs 15201:15600
Imputing SNPs 15601:16000
Imputing SNPs 16

Imputing SNPs 126401:126800
Imputing SNPs 126801:127200
Imputing SNPs 127201:127600
Imputing SNPs 127601:128000
Imputing SNPs 128001:128400
Imputing SNPs 128401:128800
Imputing SNPs 128801:129200
Imputing SNPs 129201:129600
Imputing SNPs 129601:130000
Imputing SNPs 130001:130400
Imputing SNPs 130401:130800
Imputing SNPs 130801:131200
Imputing SNPs 131201:131600
Imputing SNPs 131601:132000
Imputing SNPs 132001:132400
Imputing SNPs 132401:132800
Imputing SNPs 132801:133200
Imputing SNPs 133201:133600
Imputing SNPs 133601:134000
Imputing SNPs 134001:134400
Imputing SNPs 134401:134800
Imputing SNPs 134801:135200
Imputing SNPs 135201:135600
Imputing SNPs 135601:136000
Imputing SNPs 136001:136400
Imputing SNPs 136401:136800
Imputing SNPs 136801:137200
Imputing SNPs 137201:137600
Imputing SNPs 137601:138000
Imputing SNPs 138001:138400
Imputing SNPs 138401:138800
Imputing SNPs 138801:139200
Imputing SNPs 139201:139600
Imputing SNPs 139601:140000
Imputing SNPs 140001:140400
Imputing SNPs 140401

In [29]:
missing_impute = round.(Int, Xm.values[Xm.isnull])
error = countnz(missing_true .≠ missing_impute) / length(missing_true)

0.00011655431446341812

## Profiling

In [30]:
Profile.clear()
@profile haploimpute!(Xm, H, 400)
Profile.print(format=:flat)

Imputing SNPs 1:400
Imputing SNPs 401:800
Imputing SNPs 801:1200
Imputing SNPs 1201:1600
Imputing SNPs 1601:2000
Imputing SNPs 2001:2400
Imputing SNPs 2401:2800
Imputing SNPs 2801:3200
Imputing SNPs 3201:3600
Imputing SNPs 3601:4000
Imputing SNPs 4001:4400
Imputing SNPs 4401:4800
Imputing SNPs 4801:5200
Imputing SNPs 5201:5600
Imputing SNPs 5601:6000
Imputing SNPs 6001:6400
Imputing SNPs 6401:6800
Imputing SNPs 6801:7200
Imputing SNPs 7201:7600
Imputing SNPs 7601:8000
Imputing SNPs 8001:8400
Imputing SNPs 8401:8800
Imputing SNPs 8801:9200
Imputing SNPs 9201:9600
Imputing SNPs 9601:10000
Imputing SNPs 10001:10400
Imputing SNPs 10401:10800
Imputing SNPs 10801:11200
Imputing SNPs 11201:11600
Imputing SNPs 11601:12000
Imputing SNPs 12001:12400
Imputing SNPs 12401:12800
Imputing SNPs 12801:13200
Imputing SNPs 13201:13600
Imputing SNPs 13601:14000
Imputing SNPs 14001:14400
Imputing SNPs 14401:14800
Imputing SNPs 14801:15200
Imputing SNPs 15201:15600
Imputing SNPs 15601:16000
Imputing SNPs 16

Imputing SNPs 126401:126800
Imputing SNPs 126801:127200
Imputing SNPs 127201:127600
Imputing SNPs 127601:128000
Imputing SNPs 128001:128400
Imputing SNPs 128401:128800
Imputing SNPs 128801:129200
Imputing SNPs 129201:129600
Imputing SNPs 129601:130000
Imputing SNPs 130001:130400
Imputing SNPs 130401:130800
Imputing SNPs 130801:131200
Imputing SNPs 131201:131600
Imputing SNPs 131601:132000
Imputing SNPs 132001:132400
Imputing SNPs 132401:132800
Imputing SNPs 132801:133200
Imputing SNPs 133201:133600
Imputing SNPs 133601:134000
Imputing SNPs 134001:134400
Imputing SNPs 134401:134800
Imputing SNPs 134801:135200
Imputing SNPs 135201:135600
Imputing SNPs 135601:136000
Imputing SNPs 136001:136400
Imputing SNPs 136401:136800
Imputing SNPs 136801:137200
Imputing SNPs 137201:137600
Imputing SNPs 137601:138000
Imputing SNPs 138001:138400
Imputing SNPs 138401:138800
Imputing SNPs 138801:139200
Imputing SNPs 139201:139600
Imputing SNPs 139601:140000
Imputing SNPs 140001:140400
Imputing SNPs 140401

   937 ...pute/src/haplotyping.jl    36 haplopair!(::Tuple{Array{Int64,1},A... 
    29 ...pute/src/haplotyping.jl   102 haplopair!(::Array{Float32,2}, ::Su... 
    23 ...pute/src/haplotyping.jl   104 haplopair!(::Array{Float32,2}, ::Su... 
   107 ...pute/src/haplotyping.jl   110 haplopair!(::Array{Float32,2}, ::Su... 
     5 ...pute/src/haplotyping.jl   111 haplopair!(::Array{Float32,2}, ::Su... 
    27 ...pute/src/haplotyping.jl   112 haplopair!(::Array{Float32,2}, ::Su... 
  4698 ...pute/src/haplotyping.jl   115 haplopair!(::Array{Float32,2}, ::Su... 
    98 ...pute/src/haplotyping.jl   117 haplopair!(::Array{Float32,2}, ::Su... 
     3 ...pute/src/haplotyping.jl   189 initmissing!(::NullableArrays.Nulla... 
   275 ...pute/src/haplotyping.jl   193 initmissing!(::NullableArrays.Nulla... 
   456 ...pute/src/haplotyping.jl   194 initmissing!(::NullableArrays.Nulla... 
    46 ...pute/src/haplotyping.jl   195 initmissing!(::NullableArrays.Nulla... 
   462 ...pute/src/haplotyping.jl   196 

## Effect of window size on accuracy and efficiency

In [35]:
width_range = 20:20:100
timing = zeros(length(width_range))
errate = zeros(length(width_range))
for i in eachindex(width_range)
    tic()
    copy!(Xm.values, rawdata[1:people, :]
    haploimpute!(Xm, H, width_range[i], false)
    timing[i] = toq()
    missing_impute = round.(Int, Xm.values[Xm.isnull])
    errate[i] = countnz(missing_true .≠ missing_impute) / length(missing_true)
    println("width = $(width_range[i]), time = $(timing[i]), error rate = $(errate[i]),
        errors = $(countnz(missing_true .≠ missing_impute))")
end

width = 20, time = 118.670666731, error rate = 0.0006683833457949423,
        errors = 10930
width = 40, time = 61.575919943, error rate = 1.3514429956146591e-5,
        errors = 221
width = 60, time = 42.40008645, error rate = 1.8773438898357482e-5,
        errors = 307
width = 80, time = 33.398303239, error rate = 2.5255473175966255e-5,
        errors = 413
width = 100, time = 27.311710335, error rate = 2.9597213116628736e-5,
        errors = 484


In [36]:
using Plots
gr()

plot(width_range, timing; xlabel = "Window width", 
    ylabel = "Run time in seconds", leg = false)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 20 
 
 
 40 
 
 
 60 
 
 
 80 
 
 
 100 
 
 
 40 
 
 
 60 
 
 
 80 
 
 
 100 
 
 
 Window width 
 
 
 Run time in seconds

In [37]:
plot(width_range, errate; xlabel = "Window width", 
    ylabel = "Error rate", leg = false)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 20 
 
 
 40 
 
 
 60 
 
 
 80 
 
 
 100 
 
 
 0.0002 
 
 
 0.0004 
 
 
 0.0006 
 
 
 Window width 
 
 
 Error rate