# GBR data

In [1]:
versioninfo()

Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)


## Read in genotype data and reference panel

In [2]:
@time rawdata = readcsv("GBR_data.csv", Float32)

 24.601972 seconds (479.88 k allocations: 4.307 GiB, 3.89% gc time)


1182×163476 Array{Float32,2}:
 0.0  1.0  1.0  1.0  2.0  2.0  1.0  0.0  …  1.0  0.0  0.0  1.0  0.0  0.0  1.0
 0.0  0.0  0.0  1.0  1.0  2.0  1.0  0.0     1.0  0.0  1.0  0.0  1.0  1.0  0.0
 2.0  1.0  1.0  1.0  0.0  2.0  1.0  1.0     0.0  1.0  1.0  0.0  1.0  0.0  0.0
 1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0     0.0  1.0  1.0  0.0  1.0  1.0  1.0
 1.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  …  1.0  0.0  2.0  0.0  0.0  0.0  0.0
 1.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 1.0  0.0  1.0  1.0  2.0  0.0  1.0  1.0     0.0  1.0  1.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0     1.0  1.0  1.0  0.0  0.0  1.0  0.0
 2.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  2.0  0.0
 0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  …  0.0  0.0  1.0  0.0  1.0  0.0  0.0
 0.0  1.0  2.0  1.0  1.0  0.0  1.0  0.0     0.0  1.0  0.0  0.0  1.0  1.0  1.0
 2.0  0.0  1.0  0.0  0.0  1.0  2.0

In [3]:
people = 1000
X = rawdata[1:people, :]'

163476×1000 Array{Float32,2}:
 0.0  0.0  2.0  1.0  1.0  0.0  1.0  1.0  …  1.0  0.0  2.0  1.0  0.0  1.0  1.0
 1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0     1.0  1.0  1.0  0.0  0.0  1.0  0.0
 1.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0     1.0  0.0  0.0  1.0  0.0  1.0  1.0
 1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0     0.0  0.0  2.0  0.0  1.0  1.0  0.0
 2.0  1.0  0.0  1.0  0.0  0.0  0.0  2.0     1.0  1.0  2.0  0.0  0.0  0.0  2.0
 2.0  2.0  2.0  1.0  1.0  1.0  1.0  0.0  …  1.0  0.0  0.0  0.0  1.0  2.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     0.0  0.0  0.0  1.0  2.0  0.0  2.0
 0.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0     0.0  0.0  1.0  0.0  0.0  0.0  0.0
 1.0  0.0  1.0  1.0  1.0  0.0  1.0  1.0     0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  2.0  0.0  0.0     0.0  0.0  0.0  0.0  1.0  1.0  0.0
 0.0  0.0  1.0  1.0  0.0  1.0  0.0  1.0  …  0.0  1.0  1.0  1.0  1.0  1.0  1.0
 0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0     1.0  1.0  0.0  2.0  0.0  1.0  1.0
 1.0  1.0  1.0  0.0  0.0  1.0  1.0

In [4]:
H = rawdata[(people + 1):end, :]'

163476×182 Array{Float32,2}:
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0     0.0  0.0  1.0  1.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  1.0  1.0  0.0
 1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  1.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  …  0.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0     1.0  0.0  1.0  1.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0     1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0     0.0  1.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  …  0.0  1.0  1.0  0.0  0.0  1.0  1.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  1.0  0.0  0.0  0.0  1.0  1.0
 1.0  1.0  0.0  0.0  0.0  0.0  0.0 

## Phase + impute by moving window (using flanking windows)

In [6]:
using BenchmarkTools, MendelImpute, NullableArrays

srand(123)
missingprop = 0.1
Xm = NullableArray(X, full(sprand(Bool, size(X, 1), size(X, 2), missingprop)))
missing_true = round.(Int, X[Xm.isnull])

@time ph = phase(Xm, H, 400);

Imputing SNPs 1:400
Imputing SNPs 401:800
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 801:1200


happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 1201:1600
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 1601:2000
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 2001:2400
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 2401:2800
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 2801:3200
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 3201:3600
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 3601:4000
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 4001:4400
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 4401:4800
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 4801:5200
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 5201:5600
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 5601:6000
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 6001:6400
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 6401:6800
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 6801:7200
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 7201:7600
happair 

In [7]:
ph[64]

MendelImpute.HaplotypeMosaicPair(MendelImpute.HaplotypeMosaic(163476, [1], [16]), MendelImpute.HaplotypeMosaic(163476, [1, 26981, 93771], [73, 127, 73]))

In [8]:
@time impute!(Xm.values, H, ph)
missing_impute = round.(Int, Xm.values[Xm.isnull])
error = countnz(missing_true .≠ missing_impute) / length(missing_true)

  1.369379 seconds (108.40 k allocations: 2.441 GiB, 13.94% gc time)


4.7089850308704545e-6

In [9]:
length(missing_true) * error

77.0

## Profiling

In [13]:
Profile.clear()
@profile phase(Xm, H, 400)
Profile.print(format=:flat)

Imputing SNPs 1:400
Imputing SNPs 401:800
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 801:1200
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 1201:1600
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 1601:2000
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 2001:2400
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 2401:2800
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 2801:3200
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 3201:3600
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 3601:4000
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 4001:4400
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 4401:4800
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 4801:5200
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 5201:5600
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 5601:6000
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 6001:6400
happair = (149, 165)
bkpts = (-1, -1)
Imputing SNPs 6401:6800
happair = (149, 165)
bkpts = 

## Effect of window size on accuracy and efficiency

In [12]:
width_range = 20:20:100
timing = zeros(length(width_range))
errate = zeros(length(width_range))
for i in eachindex(width_range)
    tic()
    copy!(Xm.values, rawdata[1:people, :]')
    ph = phase(Xm, H, width_range[i], false)
    impute!(Xm.values, H, ph)
    timing[i] = toq()
    missing_impute = round.(Int, Xm.values[Xm.isnull])
    errate[i] = countnz(missing_true .≠ missing_impute) / length(missing_true)
    println("width = $(width_range[i]), time = $(timing[i]), 
        error rate = $(errate[i]),
        errors = $(countnz(missing_true .≠ missing_impute))")
end

width = 20, time = 125.53934497, 
        error rate = 0.0004522460299128183,
        errors = 7395
width = 40, time = 67.012642209, 
        error rate = 4.097428533354811e-6,
        errors = 67
width = 60, time = 48.432985235, 
        error rate = 3.6081833353422964e-6,
        errors = 59
width = 80, time = 37.98561563, 
        error rate = 3.6081833353422964e-6,
        errors = 59
width = 100, time = 32.379929152, 
        error rate = 4.158584183106376e-6,
        errors = 68


In [13]:
using Plots
gr()

plot(width_range, timing; xlabel = "Window width", 
    ylabel = "Run time in seconds", leg = false)

INFO: Recompiling stale cache file /Users/huazhou/.julia/lib/v0.6/NaNMath.ji for module NaNMath.


<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 20 
 
 
 40 
 
 
 60 
 
 
 80 
 
 
 100 
 
 
 50 
 
 
 100 
 
 
 Window width 
 
 
 Run time in seconds

In [14]:
plot(width_range, errate; xlabel = "Window width", 
    ylabel = "Error rate", leg = false)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 20 
 
 
 40 
 
 
 60 
 
 
 80 
 
 
 100 
 
 
 0.0001 
 
 
 0.0002 
 
 
 0.0003 
 
 
 0.0004 
 
 
 Window width 
 
 
 Error rate